# Cloudflare Pages Wrangler Configuration
name = "proam-rankings"
compatibility_date = "2024-01-01"

# Cron Triggers for Scheduled Functions
# These run automatically on the specified schedule

[[triggers]]
# Update player ratings daily at 2:00 AM UTC
# This applies decay penalties and recalculates ratings
crons = ["0 2 * * *"]

# Environment Variables
# These should be set in the Cloudflare Pages Dashboard:
# Settings -> Environment variables
#
# Required variables:
# - SUPABASE_URL: Your Supabase project URL
# - SUPABASE_ANON_KEY: Your Supabase anonymous key

